/**
 * Copyright (c) 2014-2017 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.bluetooth.bluegiga.command.system;

import com.zsmartsystems.bluetooth.bluegiga.BlueGigaCommand;

/**
 * Class to implement the BlueGiga command <b>reset</b>.
 * <p>
 * This command resets the local device immediately. The command does not have a response.
 * <p>
 * This class provides methods for processing BlueGiga API commands.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class BlueGigaResetCommand extends BlueGigaCommand {
    public static int COMMAND_CLASS = 0x00;
    public static int COMMAND_METHOD = 0x00;

    /**
     * Selects the boot mode. 0 : boot to main program. 1 : boot to DFU
     * <p>
     * BlueGiga API type is <i>uint8</i> - Java type is {@link int}
     */
    private int boot_in_dfu;
    /**
     * Selects the boot mode. 0 : boot to main program. 1 : boot to DFU
     *
     * @param boot_in_dfu the boot_in_dfu to set as {@link int}
     */
    public void setBoot_in_dfu(int boot_in_dfu) {
        this.boot_in_dfu = boot_in_dfu;
    }


    @Override
    public int[] serialize() {
        // Serialize the header
        serializeHeader(COMMAND_CLASS, COMMAND_METHOD);

        // Serialize the fields
        serializeUInt8(boot_in_dfu);

        return getPayload();
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append("BlueGigaResetCommand [boot_in_dfu=");
        builder.append(boot_in_dfu);
        builder.append("]");
        return builder.toString();
    }
}
