/**
 * Copyright (c) 2014-2017 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.bluetooth.bluegiga.command.gap;

import com.zsmartsystems.bluetooth.bluegiga.BlueGigaCommand;

/**
 * Class to implement the BlueGiga command <b>setAdvData</b>.
 * <p>
 * This commands set advertisement or scan response data used in the advertisement and scan
 * response packets. The command allows application specific data to be broadcasts either in
 * advertisement or scan response packets. The data set with this command is only used when the
 * GAP discoverable mode is set to gap_user_data. Notice that advertisement or scan response
 * data must be formatted in accordance to the Bluetooth Core Specification. See BLUETOOTH
 * SPECIFICATION Version 4.0 [Vol 3 - Part C - Chapter 11].
 * <p>
 * This class provides methods for processing BlueGiga API commands.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class BlueGigaSetAdvDataCommand extends BlueGigaCommand {
    public static int COMMAND_CLASS = 0x06;
    public static int COMMAND_METHOD = 0x09;

    /**
     * Advertisement data type. 0 : sets advertisement data. 1 : sets scan response data
     * <p>
     * BlueGiga API type is <i>uint8</i> - Java type is {@link int}
     */
    private int set_scanrsp;

    /**
     * Advertisement data to send
     * <p>
     * BlueGiga API type is <i>uint8array</i> - Java type is {@link int[]}
     */
    private int[] adv_data;
    /**
     * Advertisement data type. 0 : sets advertisement data. 1 : sets scan response data
     *
     * @param set_scanrsp the set_scanrsp to set as {@link int}
     */
    public void setSet_scanrsp(int set_scanrsp) {
        this.set_scanrsp = set_scanrsp;
    }

    /**
     * Advertisement data to send
     *
     * @param adv_data the adv_data to set as {@link int[]}
     */
    public void setAdv_data(int[] adv_data) {
        this.adv_data = adv_data;
    }


    @Override
    public int[] serialize() {
        // Serialize the header
        serializeHeader(COMMAND_CLASS, COMMAND_METHOD);

        // Serialize the fields
        serializeUInt8(set_scanrsp);
        serializeUInt8Array(adv_data);

        return getPayload();
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append("BlueGigaSetAdvDataCommand [set_scanrsp=");
        builder.append(set_scanrsp);
        builder.append(", adv_data=");
        builder.append(adv_data);
        builder.append("]");
        return builder.toString();
    }
}
