/**
 * Copyright (c) 2014-2017 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.zsmartsystems.bluetooth.bluegiga.command.attributeclient;

import com.zsmartsystems.bluetooth.bluegiga.BlueGigaResponse;

/**
 * Class to implement the BlueGiga command <b>procedureCompletedEvent</b>.
 * <p>
 * This event is produced at the GATT client when an attribute protocol event is completed a and
 * new operation can be issued
 * <p>
 * This class provides methods for processing BlueGiga API commands.
 * <p>
 * Note that this code is autogenerated. Manual changes may be overwritten.
 *
 * @author Chris Jackson - Initial contribution of Java code generator
 */
public class BlueGigaProcedureCompletedEvent extends BlueGigaResponse {
    public static int COMMAND_CLASS = 0x04;
    public static int COMMAND_METHOD = 0x01;

    /**
     * Connection handle
     * <p>
     * BlueGiga API type is <i>uint8</i> - Java type is {@link int}
     */
    private int connection;

    /**
     * Attribute value
     * <p>
     * BlueGiga API type is <i>uint16</i> - Java type is {@link int}
     */
    private int result;

    /**
     * Characteristic handle at which the event ended
     * <p>
     * BlueGiga API type is <i>uint16</i> - Java type is {@link int}
     */
    private int chrhandle;

    /**
     * Event constructor
     */
    public BlueGigaProcedureCompletedEvent(int[] inputBuffer) {
        // Super creates deserializer and reads header fields
        super(inputBuffer);

        // Deserialize the fields
        connection = deserializeUInt8();
        result = deserializeUInt16();
        chrhandle = deserializeUInt16();
    }

    /**
     * Connection handle
     * <p>
     * BlueGiga API type is <i>uint8</i> - Java type is {@link int}
     *
     * @return the current connection as {@link int}
     */
    public int getConnection() {
        return connection;
    }

    /**
     * Attribute value
     * <p>
     * BlueGiga API type is <i>uint16</i> - Java type is {@link int}
     *
     * @return the current result as {@link int}
     */
    public int getResult() {
        return result;
    }

    /**
     * Characteristic handle at which the event ended
     * <p>
     * BlueGiga API type is <i>uint16</i> - Java type is {@link int}
     *
     * @return the current chrHandle as {@link int}
     */
    public int getChrhandle() {
        return chrhandle;
    }


    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append("BlueGigaProcedureCompletedEvent [connection=");
        builder.append(connection);
        builder.append(", result=");
        builder.append(result);
        builder.append(", chrhandle=");
        builder.append(chrhandle);
        builder.append(']');
        return builder.toString();
    }
}
